name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Add the PEM key as an SSH key
      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@3.108.84.213 << 'EOF'
            cd /home/ec2-user/siddha-connect-backend
            
            # Ensure correct Node.js version is used
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 18 || nvm use default
            
            # Pull latest changes from Git
            git fetch --all
            git reset --hard origin/main
            git pull origin main
            
            # Install dependencies
            npm install --production
            
            # Restart PM2 with updated environment variables
            pm2 restart siddha-connect-v2 --update-env || pm2 start server.js --name siddha-connect-v2
            
            # Save PM2 process for reboot persistence
            pm2 save
            
            # Ensure PM2 auto-starts on reboot
            pm2 startup systemd --user ec2-user --hp /home/ec2-user
          EOF
