name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Add the PEM key as an SSH key
      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      # Step 3: Connect to EC2 instance and deploy
      - name: Deploy to EC2
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@3.108.84.213 << 'EOF'
            # Check if Node.js and PM2 are installed, else install them
            if ! [ -x "$(command -v node)" ]; then
              curl -sL https://rpm.nodesource.com/setup_20.x | sudo bash -
              sudo yum install -y nodejs
            fi
            if ! [ -x "$(command -v pm2)" ]; then
              sudo npm install -g pm2
            fi

            # Navigate to project directory
            cd /home/ec2-user/siddha-connect-backend

            # Stop the PM2 process
            pm2 stop server || true

            # Pull the latest code
            git pull origin main || exit 1

            # Install project dependencies
            npm install --unsafe-perm=true || exit 1

            # Start the PM2 process
            pm2 start server || exit 1

            # Save PM2 configuration
            pm2 save || true
            pm2 startup systemd -u ec2-user --hp /home/ec2-user || true
          EOF
