name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Add the PEM key as an SSH key
      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      # Step 3: Connect to EC2 instance and deploy
      - name: Deploy to EC2
        run: |
          sudo su
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@3.108.84.213 << 'EOF'
            # Update the instance and install Node.js if necessary
            sudo yum update -y
            curl -sL https://rpm.nodesource.com/setup_20.x | sudo bash -
            sudo yum install -y nodejs

            # Install PM2 globally
            sudo npm install -g pm2

            # Navigate to project directory
            # cd /root

            # Pull the latest code
            git pull origin main

            # Install project dependencies
            npm install

            # Restart the app using PM2
            pm2 delete all || true
            pm2 start server.js --name="server" -f

            # Save PM2 configuration
            pm2 save
            pm2 startup
          EOF
