name: Node.js CI/CD

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Add the PEM key as an SSH key
      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      # Step 3: Connect to EC2 instance and deploy
      - name: Deploy to EC2
        run: |
          ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@3.108.84.213 << 'EOF'
            cd /home/ec2-user/siddha-connect-backend
            sudo su
            git pull origin main
            npm install
            pm2 restart siddha-connect-backend || pm2 start server.js --name siddha-connect-backend
            pm2 save
          EOF
